# Generated by Django 4.0.4 on 2023-03-04 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Work_board_app', '0003_alter_work_time_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_time',
            name='target_user',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='対象者'),
        ),
    ]
